export PROJECT = inventory-backend
IMPORT_PATH := ${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/... \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/... \
    --link inventory-backend-mongo-db:inventory-backend-mongo-db \
    ${DEV_IMAGE}
